#!/usr/bin/env bash

set -euo pipefail

function install-bin {
  bin=${1}
  url=${2}
  echo "Installing: ${bin}"
  curl --location -o "/tmp/${bin}" "${url}"
  sudo cp "/tmp/${bin}" "/usr/bin/${bin}"
  sudo chmod +x "/usr/bin/${bin}"
}

install-bin mak "https://github.com/lgarron/mak/raw/bin/mak_x86_64-linux"
