#!/usr/bin/env fish

# For Codespaces
# https://docs.github.com/en/free-pro-team@latest/github/developing-online-with-codespaces/personalizing-codespaces-for-your-account

sudo chsh -s (which fish)

set CURRENT_DIR (status --current-filename)

source $CURRENT_DIR/dotfiles/fish/.config/fish/config.fish
source $CURRENT_DIR/dotfiles/fish/.config/fish/git.fish
