#!/usr/bin/env bash

set -euo pipefail

# For Codespaces
# https://docs.github.com/en/free-pro-team@latest/github/developing-online-with-codespaces/personalizing-codespaces-for-your-account

cd "$(dirname "$0")"

sudo apt install -y fish stow
brew install --HEAD lgarron/lgarron/git-freeze
make fish
