# .zshrc Customization
# Lucas Garron, 2012

# oh-my-zsh settings
ZSH=$HOME/Documents/git/GitHub-clones/oh-my-zsh
ZSH_THEME="sunrise"
DISABLE_AUTO_TITLE="true"
COMPLETION_WAITING_DOTS="true"
plugins=(git osx)

source $ZSH/oh-my-zsh.sh

# Shortcuts

## Editors
alias subl="/Applications/Tools/Sublime\ Text\ 2.app/Contents/SharedSupport/bin/subl"
export EDITOR="subl -w"
alias e='emacs'
alias s='subl'

alias resrc="source ~/.zshrc"

## Hashes
alias md5='openssl md5'
alias sha='openssl sha'

alias battery='ioreg -rc AppleSmartBattery'

## Search
alias f='find . -iname'
alias o='open .' # Open pwd in Finder.

## Git shortcuts
alias g="git"
alias gs="git status"
alias gl="git log"
alias glp="git log --oneline --decorate=full --graph --remotes" # git log pretty, from http://www.xerxesb.com/2010/command-line-replacement-for-gitk/
alias gd="git diff"
alias gdi="git difftool -t fmdiff"
#function gst {
#  git stage "$@"
#  gs
#}
alias gst="git stage"
alias gc="git commit -m"
alias gco="git checkout"
alias gcb="git checkout -b"
alias gca="git commit --amend"
alias gb="git branch"
alias gh="github"

# Server from the current directory.
# From http://apple.stackexchange.com/questions/5435/got-any-tips-or-tricks-for-terminal-in-mac-os-x
serve() { open "http://localhost:${1:-8080}/" &&  python -m SimpleHTTPServer ${1:-8080}; }

alias screensaver_desktop="/System/Library/Frameworks/ScreenSaver.framework/Resources/ScreenSaverEngine.app/Contents/MacOS/ScreenSaverEngine -background"

# Random password generator
function makepass() { head /dev/random | uuencode -m - | sed -n 2p | cut -c1-${1:-20}; }
alias word='sed `perl -e "print int rand(99999)"`"q;d" /usr/share/dict/words | tr -d "\\n"'
function makewords() {
  echo "`word`-`word`-`word`-`word`"
}

# ${PATH} additions
export PATH="~/Documents/Code/executable/bin/:$PATH"
path=(~/Documents/Code/executable/bin/ ${path}) #zsh

# Echonest Remix API.
export ECHO_NEST_API_KEY="EJ7ZVMPNXWVFXS1KE"


# Application aliases
alias audacity="open -a /Applications/Tools/Audacity.app/"
alias gimp="open -a /Applications/Tools/Gimp.app"
