#!/usr/bin/env bash

set -euo pipefail

function install-lgarron-script {
  dest_bin=${1}
  src_bin=${2}
  echo "Installing: ${dest_bin}"
  sudo cp "scripts/${src_bin}" "/usr/bin/${dest_bin}"
  sudo chmod +x "/usr/bin/${dest_bin}"
}

function install-lgarron-script-with-completions {
  script="${1}"
  install-lgarron-script "$@"
  mkdir -p "${HOME}/.config/fish/completions"
  "/usr/bin/${script}" --completions fish > "${HOME}/.config/fish/completions/${script}.fish"
}

command -v version || install-lgarron-script version git/version.fish
command -v git-distance || install-lgarron-script git-distance git/git-distance.fish

command -v rmbranch || install-lgarron-script-with-completions rmbranch git/rmbranch.fish
command -v rmtag || install-lgarron-script-with-completions rmtag git/rmtag.fish
