hs.hotkey.bind({"cmd", "ctrl"}, "H", function()
  hs.eventtap.keyStroke({"cmd"}, "left")
end)
hs.hotkey.bind({"alt", "ctrl"}, "H", function()
  hs.eventtap.keyStroke({"alt"}, "left")
end)
hs.hotkey.bind({"ctrl"}, "H", function()
  hs.eventtap.keyStroke({}, "left")
end)

hs.hotkey.bind({"cmd", "ctrl"}, "J", function()
  hs.eventtap.keyStroke({"cmd"}, "down")
end)
hs.hotkey.bind({"alt", "ctrl"}, "J", function()
  hs.eventtap.keyStroke({"alt"}, "down")
end)
hs.hotkey.bind({"ctrl"}, "J", function()
  hs.eventtap.keyStroke({}, "down")
end)

hs.hotkey.bind({"cmd", "ctrl"}, "K", function()
  hs.eventtap.keyStroke({"cmd"}, "up")
end)
hs.hotkey.bind({"alt", "ctrl"}, "K", function()
  hs.eventtap.keyStroke({"alt"}, "up")
end)
hs.hotkey.bind({"ctrl"}, "K", function()
  hs.eventtap.keyStroke({}, "up")
end)

hs.hotkey.bind({"cmd", "ctrl"}, "L", function()
  hs.eventtap.keyStroke({"cmd"}, "right")
end)
hs.hotkey.bind({"alt", "ctrl"}, "L", function()
  hs.eventtap.keyStroke({"alt"}, "right")
end)
hs.hotkey.bind({"ctrl"}, "L", function()
  hs.eventtap.keyStroke({}, "right")
end)
