#!/usr/bin/env bash

set -euo pipefail

# For Codespaces
# https://docs.github.com/en/codespaces/customizing-your-codespace/personalizing-github-codespaces-for-your-account#dotfiles

cd "$(dirname "$0")"
cd ..

if ! command -v stow
then
  echo "Installing \`stow\`."
  sudo add-apt-repository --yes http://archive.ubuntu.com/ubuntu/ || echo "🤷" # *sigh* https://askubuntu.com/a/1132852 # TODO: Make this more portable across Debian OSes.
  sudo apt-get install -y stow

  # Note: we would install `fish` together with `stow`, but most default PPAs are 3 years of date. So we don't even bother, and handle `fish` separately below.
fi

if [ -n "$CODESPACES" ]
then
  rm -rf \
    ~/.config/fish/config.fish \
    ~/.local/share/fish || rm -rf \
    ~/.config/fish/config.fish \
    ~/.local/share/fish
fi
make linux

sudo chsh "$(id -un)" --shell "$(command -v fish)"

cd "$(dirname "$0")"
./install-git-commands
./install-lgarron-scripts
./install-mak
