#!/usr/bin/env bash

set -euo pipefail

# For Codespaces
# https://docs.github.com/en/codespaces/customizing-your-codespace/personalizing-github-codespaces-for-your-account#dotfiles

cd "$(dirname "$0")"
cd ..

sudo add-apt-repository http://archive.ubuntu.com/ubuntu/ # *sigh* https://askubuntu.com/a/1132852 # TODO: Make this more portable across Debian OSes.
sudo apt-get install -y fish stow
make fish

cd "$(dirname "$0")"
./raw-git-freeze-install
