#!/usr/bin/env bash

set -euo pipefail

# For Codespaces
# https://docs.github.com/en/codespaces/customizing-your-codespace/personalizing-github-codespaces-for-your-account#dotfiles

cd "$(dirname "$0")"
cd ..

sudo apt-get install -y fish stow
make fish

cd "$(dirname "$0")"
./raw-git-freeze-install
