#!/usr/bin/env bash

set -euo pipefail

function install-git-freeze-bin {
  bin=${1}
  echo "Installing: ${bin}"
  curl -o "/tmp/${bin}" "https://raw.githubusercontent.com/lgarron/git-freeze/main/bin/${bin}"
  sudo cp "/tmp/${bin}" "/usr/bin/${bin}"
  sudo chmod +x "/usr/bin/${bin}"
}

which git-freeze || install-git-freeze-bin git-freeze
which git-thaw || install-git-freeze-bin git-thaw
which git-abandon || install-git-freeze-bin git-abandon

function install-scripts-bin {
  bin=${1}
  echo "Installing: ${bin}"
  curl -o "/tmp/${bin}" "https://raw.githubusercontent.com/lgarron/scripts/main/git/${bin}"
  sudo cp "/tmp/${bin}" "/usr/bin/${bin}"
  sudo chmod +x "/usr/bin/${bin}"
}

which git-distance || install-scripts-bin git-distance
