#!/usr/bin/env bash

set -euo pipefail

function install-git-freeze-bin {
  bin=${1}
  echo "Installing: ${bin}"
  curl -o "/tmp/${bin}" "https://raw.githubusercontent.com/lgarron/git-freeze/main/bin/${bin}"
  sudo cp "/tmp/${bin}" "/usr/bin/${bin}"
  sudo chmod +x "/usr/bin/${bin}"
}

command -v git-freeze || install-git-freeze-bin git-freeze
command -v git-thaw || install-git-freeze-bin git-thaw
command -v git-abandon || install-git-freeze-bin git-abandon

function install-scripts-bin {
  src_bin=${1}
  dest_bin=${2}
  echo "Installing: ${dest_bin}"
  curl -o "/tmp/${dest_bin}" "https://raw.githubusercontent.com/lgarron/scripts/main/${src_bin}"
  sudo cp "/tmp/${dest_bin}" "/usr/bin/${dest_bin}"
  sudo chmod +x "/usr/bin/${dest_bin}"
}

command -v git-distance || install-scripts-bin git/git-distance.fish git-distance
