[revsets]
# Adapted from: https://willhbr.net/2024/08/18/understanding-revsets-for-a-better-jj-log-output/
log = "@ | ancestors(visible_heads(), 5)"

[revset-aliases]
# Adapted from https://github.com/jj-vcs/jj/discussions/4012#discussioncomment-12685567
'here' = 'coalesce(@ ~ empty(), @-)'
