name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - uses: dtolnay/rust-toolchain@nightly
      - run: cargo run --bin openscad-auto -- --completions fish

  bootstrap:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - run: env CODESPACES=true ./bootstrap.sh
