[revsets]
# Adapted from: https://willhbr.net/2024/08/18/understanding-revsets-for-a-better-jj-log-output/
log = "@ | ancestors(visible_heads() | tracked_remote_bookmarks(), 20)"

[revset-aliases]
# TODO: make the ancestor hierarchy consistent.
# Adapted from https://github.com/jj-vcs/jj/discussions/4012#discussioncomment-12685567
'closest_nonempty_ancestor(to)' = 'latest(heads(::to & (~empty() )))'
'closest_ancestor_bookmark(to)' = 'latest(heads(::to & bookmarks()))'
# TODO: add `mutable()`? https://github.com/jj-vcs/jj/discussions/5568#discussioncomment-13007551
'closest_pushable_ancestor(to)' = 'latest(heads(::to & ~description(exact:"") & (~empty() | merges())))'
'here' = 'closest_pushable_ancestor(@)'

[aliases]
tug = [
  "bookmark",
  "move",
  "--from",
  "closest_ancestor_bookmark(@)",
  "--to",
  "closest_pushable_ancestor(@)",
]
here = [
  "log",
  "--no-graph",
  "--ignore-working-copy",
  "--revisions",
  "here",
  "--template",
  "commit_id",
]
guess-branch = [
  "log",
  "--no-graph",
  "--ignore-working-copy",
  "--revisions",
  "closest_ancestor_bookmark(@)",
  "--template",
  "bookmarks.map(|b| b.name())",
]
guess-branch-maybe-divergent = [
  "log",
  "--no-graph",
  "--ignore-working-copy",
  "--revisions",
  "closest_ancestor_bookmark(@)",
  "--template",
  "bookmarks",
]

[git]
push-new-bookmarks = true
