[revsets]
# Adapted from: https://willhbr.net/2024/08/18/understanding-revsets-for-a-better-jj-log-output/
log = "@ | ancestors(visible_heads() | tracked_remote_bookmarks(), 20)"

[revset-aliases]
# Adapted from https://github.com/jj-vcs/jj/discussions/4012#discussioncomment-12685567
'closest_nonempty_ancestor(to)' = 'heads(::to & (~empty() ))'
'closest_nonempty_ancestor(to, max_depth)' = 'heads(ancestors(to, max_depth) & ~empty())'
'closest_ancestor_bookmark(to)' = 'heads(::to & bookmarks())'
'closest_ancestor_bookmark(to, max_depth)' = 'heads(ancestors(to, max_depth) & bookmarks())'
# TODO: add `mutable()`? https://github.com/jj-vcs/jj/discussions/5568#discussioncomment-13007551
'closest_pushable_ancestor(to)' = 'heads(::to & ~description(exact:"") & (~empty() | merges()))'
'closest_pushable_ancestor(to, max_depth)' = 'heads(ancestors(to, max_depth) & ~description(exact:"") & (~empty() | merges()))'
'here' = 'closest_pushable_ancestor(@)'
'here(max_depth)' = 'closest_pushable_ancestor(@, max_depth)'

[aliases]
tug = [
  "bookmark",
  "move",
  "--from",
  "closest_ancestor_bookmark(@)",
  "--to",
  "closest_pushable_ancestor(@)",
]
here = [
  "log",
  "--no-graph",
  "--ignore-working-copy",
  "--revisions",
  "here",
  "--template",
  "commit_id",
]
guess-branch = [
  "log",
  "--no-graph",
  "--ignore-working-copy",
  "--color=never",
  "--revisions",
  "closest_ancestor_bookmark(@)",
  "--template",
  "bookmarks.map(|b| b.name()).join(\"\n\")",
]

[git]
push-new-bookmarks = true
