[revsets]
# Adapted from: https://willhbr.net/2024/08/18/understanding-revsets-for-a-better-jj-log-output/
log = "@ | ancestors(visible_heads() | tracked_remote_bookmarks(), 20)"

[revset-aliases]
'ancestor_bookmarks(to)' = 'heads(::to & bookmarks())'
'single_latest_ancestor_bookmark(to)' = 'latest(ancestor_bookmarks(to))'

# bookhere
'bookhere' = 'single_latest_ancestor_bookmark(@)'
'bookhere_descendants_to_working_copy' = 'bookhere+::@'
'bookhere_descendants_to_working_copy(from)' = '(bookhere_descendants_to_working_copy & from)+::@'
'bookhere_descendants_to(to)' = 'bookhere+::to'
'pushable_bookhere' = 'bookhere_descendants_to_working_copy & individually_pushable'

# Helpers for `bookhere` and prompt.
'blank' = '(empty() & ~merges())'
'undescribed' = 'description(exact:"")'
'individually_pushable' = '~undescribed & ~blank'

# For prompt
'pushable_stack_bookhere' = 'pushable_bookhere & ~bookhere_descendants_to_working_copy(~individually_pushable)'
'blank_fringe_bookhere' = 'bookhere_descendants_to_working_copy & blank & ~bookhere_descendants_to(~blank)'
'draft_bookhere' = 'bookhere_descendants_to_working_copy & ~pushable_stack_bookhere & ~blank_fringe_bookhere'

'here' = 'latest(pushable_stack_bookhere)'

[aliases]
tug = [
  "bookmark",
  "move",
  "--from",
  "single_latest_ancestor_bookmark(@)",
  "--to",
  "here",
]
here = [
  "log",
  "--no-graph",
  "--ignore-working-copy",
  "--revisions",
  "here",
  "--template",
  "commit_id",
]
guess-branch = [
  "log",
  "--no-graph",
  "--ignore-working-copy",
  "--revisions",
  "single_latest_ancestor_bookmark(@)",
  "--template",
  "bookmarks.map(|b| b.name())",
]
guess-branch-maybe-divergent = [
  "log",
  "--no-graph",
  "--ignore-working-copy",
  "--revisions",
  "single_latest_ancestor_bookmark(@)",
  "--template",
  "bookmarks",
]

[git]
push-new-bookmarks = true
