[git]
push-new-bookmarks = true

[revsets]
# Adapted from: https://willhbr.net/2024/08/18/understanding-revsets-for-a-better-jj-log-output/
log = "@ | ancestors(visible_heads() | tracked_remote_bookmarks(), 20)"

[revset-aliases]
'ancestor_bookmarks(to)' = 'heads(::to & bookmarks())'
'single_latest_ancestor_bookmark(to)' = 'latest(ancestor_bookmarks(to))'
'single_latest_ancestor_bookmark_or_fork_point(to)' = 'latest(coalesce(ancestor_bookmarks(to), fork_point(to | bookmarks(exact:"main")), fork_point(to | trunk())))'

# promptanchor
'promptanchor' = 'single_latest_ancestor_bookmark_or_fork_point(@)'
'promptanchor_descendants_to_working_copy' = 'promptanchor+::@'
'promptanchor_descendants_to_working_copy(from)' = '(promptanchor_descendants_to_working_copy & from)+::@'
'promptanchor_descendants_to(to)' = 'promptanchor+::to'
'promptanchor_individually_pushable' = 'promptanchor_descendants_to_working_copy & individually_pushable'

# Helpers for prompt.
'blank' = '(empty() & ~merges())'
'undescribed' = 'description(exact:"")'
'individually_pushable' = '~undescribed & ~blank'

# For prompt
'prompt_pushable_stack' = 'promptanchor_individually_pushable & ~promptanchor_descendants_to_working_copy(~individually_pushable)'
'prompt_blank_fringe' = 'promptanchor_descendants_to_working_copy & blank & ~promptanchor_descendants_to(~blank)'
'prompt_draft' = 'promptanchor_descendants_to_working_copy & ~prompt_pushable_stack & ~prompt_blank_fringe'

'here' = 'latest(heads(promptanchor | prompt_pushable_stack))'

[aliases]
tug = [
  "bookmark",
  "move",
  "--from",
  "single_latest_ancestor_bookmark(@)",
  "--to",
  "here",
]
here = [
  "log",
  "--no-graph",
  "--ignore-working-copy",
  "--revisions",
  "here",
  "--template",
  "commit_id",
]
# - Never includes trailing `*`.
# - Prioritizes `main` over other branch names. (`master` is not treated specially.)
guess-branch = [
  "log",
  "--no-graph",
  "--ignore-working-copy",
  "--revisions",
  "single_latest_ancestor_bookmark(@)",
  "--template",
  "if(bookmarks.filter(|b| b.name() == \"main\"), \"main\", stringify(bookmarks.map(|b| b.name()).join(\"\n\")).first_line())",
]
# - May include trailing `*`.
# - Prioritizes `main` over other branch names. (`master` is not treated specially.)
guess-branch-pretty = [
  "log",
  "--no-graph",
  "--ignore-working-copy",
  "--revisions",
  "single_latest_ancestor_bookmark(@)",
  "--template",
  "if(bookmarks.filter(|b| b.name() == \"main\"), label(\"bookmark\", stringify(bookmarks.filter(|b| b.name() == \"main\").join(\"\n\")).first_line()), label(\"bookmark\", stringify(bookmarks.join(\"\n\")).first_line()))",
]
# - Never includes trailing `*`.
# - Prioritizes `main` over other branch names. (`master` is not treated specially.)
prompt-anchor = [
  "log",
  "--no-graph",
  "--ignore-working-copy",
  "--revisions",
  "single_latest_ancestor_bookmark_or_fork_point(@)",
  "--template",
  "if(bookmarks.len() > 0, if(bookmarks.filter(|b| b.name() == \"main\"), \"main\", stringify(bookmarks.map(|b| b.name()).join(\"\n\")).first_line()), change_id.shortest())",
]
# - May include trailing `*`.
# - Prioritizes `main` over other branch names. (`master` is not treated specially.)
prompt-anchor-pretty = [
  "log",
  "--no-graph",
  "--ignore-working-copy",
  "--revisions",
  "single_latest_ancestor_bookmark_or_fork_point(@)",
  "--template",
  "if(bookmarks.len() > 0, if(bookmarks.filter(|b| b.name() == \"main\"), label(\"bookmark\", stringify(bookmarks.filter(|b| b.name() == \"main\").join(\"\n\")).first_line()), label(\"bookmark\", stringify(bookmarks.join(\"\n\")).first_line())), change_id.shortest())",
]

# TODO: figure out why `repo version bump --commit dev` has a tendency to cause this. Maybe a race condition with `gg.app`?
sweep = [
  "abandon",
  "empty() & ~merges() & description(exact:\"\") & ~bookmarks() & ~immutable() & ~root() & ~@",
]

[ui]
diff-editor = ":builtin"
