[revsets]
# Adapted from: https://willhbr.net/2024/08/18/understanding-revsets-for-a-better-jj-log-output/
log = "@ | ancestors(visible_heads() | tracked_remote_bookmarks(), 20)"

[revset-aliases]
'ancestor_bookmarks(to)' = 'heads(::to & bookmarks())'
'single_latest_ancestor_bookmark(to)' = 'latest(ancestor_bookmarks(to))'
'bookhere' = 'single_latest_ancestor_bookmark(@)'

# Levels:
# - Pushable: described and (non-empty or merge)
# - Undescribed: non-empty or merge, not pushable
# - Empty: Empty, undescribed
'empty_nonmerges' = '(empty() & ~merges())'
'undescribed' = 'description(exact:"")'
'undescribed_nonempty' = 'undescribed & ~empty_nonmerges'
'undescribed_empty' = 'undescribed & empty_nonmerges'
'individually_pushable' = '~undescribed & ~empty_nonmerges'
# TODO: is it safe to use `heads(from)+::@`?
'descendants(from)' = 'from+::@'
#'continuous(condition)' = 'condition & ~((~(condition))::@)'

'pushable_bookhere' = 'descendants(bookhere) & individually_pushable'
'pushable_bookhere_descendants' = 'descendants(pushable_bookhere)'
'undescribed_nonempty_bookhere' = 'descendants(bookhere) & undescribed_nonempty'
'undescribed_nonempty_bookhere_descendants' = 'descendants(undescribed_nonempty_bookhere)'
'empty_bookhere' = 'descendants(bookhere) & undescribed_empty'
'empty_bookhere_descendants' = 'descendants(empty_bookhere)'

'pushable_orphans_bookhere' = 'pushable_bookhere & undescribed_nonempty_bookhere_descendants'
'undescribed_orphans_bookhere' = 'undescribed_nonempty_bookhere & empty_bookhere_descendants'

'pushable_stack_bookhere' = 'pushable_bookhere & ~undescribed_nonempty_bookhere_descendants'
'undescribed_stack_bookhere' = 'undescribed_nonempty_bookhere & ~empty_bookhere_descendants'
'empty_stack_bookhere' = 'empty_bookhere & ~(descendants(pushable_orphans_bookhere)) & ~(descendants(undescribed_orphans_bookhere))'
'disordered_bookhere' = 'descendants(bookhere) & ~pushable_stack_bookhere & ~undescribed_stack_bookhere & ~empty_stack_bookhere'

#'single_closest_pushable_ancestor(to)' = 'latest(pushable_in_range(::to))'
'here' = 'latest(pushable_stack_bookhere)'

[aliases]
tug = [
  "bookmark",
  "move",
  "--from",
  "single_latest_ancestor_bookmark(@)",
  "--to",
  "here",
]
here = [
  "log",
  "--no-graph",
  "--ignore-working-copy",
  "--revisions",
  "here",
  "--template",
  "commit_id",
]
guess-branch = [
  "log",
  "--no-graph",
  "--ignore-working-copy",
  "--revisions",
  "single_latest_ancestor_bookmark(@)",
  "--template",
  "bookmarks.map(|b| b.name())",
]
guess-branch-maybe-divergent = [
  "log",
  "--no-graph",
  "--ignore-working-copy",
  "--revisions",
  "single_latest_ancestor_bookmark(@)",
  "--template",
  "bookmarks",
]

[git]
push-new-bookmarks = true
